project_id = "rhfpalxnabxibepvpfgy"

[functions.admin-create-user]
verify_jwt = true

[functions.admin-reset-password]
verify_jwt = true

[functions.qr-create-order]
verify_jwt = false

[functions.confirm-qr-order]
verify_jwt = false

[functions.reject-qr-order]
verify_jwt = false