project_id = "rhfpalxnabxibepvpfgy"

[functions.admin-create-user]
verify_jwt = true

[functions.admin-reset-password]
verify_jwt = true

[functions.qr-create-order]
verify_jwt = false

[functions.confirm-qr-order]
verify_jwt = false

[functions.reject-qr-order]
verify_jwt = false

[functions.set-restaurant-active]
verify_jwt = false

[functions.update-cashier-status]
verify_jwt = false

[functions.complete-payment]
verify_jwt = false